### ISSUE TITLE
rosbag HPS-3D160 lidar available?

### ISSUE THREAD

**Issue by fnaser** [xmba15/hypersen_lidar#1]
Hi @xmba15,

Would it be possible for you to share a short rosbag with sample data of the HPS-3D160 lidar? Is a an accurate range measurement possible up to 15m as indicated in the sensor specs https://en.hypersen.com/product/detail/10.html? Would be interested to test the point clouds before ordering the sensor.

Thank you and best regards,
Felix

**Comment by xmba15** [comment]
Hi Felix, 
Sorry, I don't have sample point cloud in my PC now.
The lidar is company belonging and I have to work from home now due to the pandemic; hence don't know when I can reach the lidar again to store a short rosbag data for you.

For the precision of the lidar, I actually did a simple comparison between the distance of the obstacle point cloud obtained from the lidar and the real distance to that obstacle (using a laser measurement device), the offset was about 10 cm between the two values. The manual also mentions that offset and recommends the user to measure the value by himself.

For the maximum range, sadly I did conduct any experiments to confirm.
